version: "3.9"

services:
  backend:
    image: 'mytodo-backend:latest'
    build:
      context: .
    container_name: backend
    depends_on:
      - database
    ports:
      - "8080:8080"

  database:
    build: ./src/docker/database

  frontend:
    image: 'mytodo-frontend:latest'
    build:
      context: ./src/webapp
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"